#!/bin/bash

# Script para diagnosticar problemas del backend en Azure
# Identifica y propone soluciones para errores 503

echo "=== Diagnóstico de Problemas del Backend ==="
echo ""

BACKEND_URL="https://evaluador-backend-fzbhemgtetfeeme6.spaincentral-01.azurewebsites.net"
APP_NAME="evaluador-backend-fzbhemgtetfeeme6"
RESOURCE_GROUP="evaluador-rg"

echo "Backend URL: $BACKEND_URL"
echo "App Service: $APP_NAME"
echo "Resource Group: $RESOURCE_GROUP"
echo ""

echo "=== Posibles Causas del Error 503 ==="
echo ""
echo "1. ❌ Aplicación no iniciada o crasheada"
echo "2. ❌ Dependencias faltantes (requirements.txt)"
echo "3. ❌ Variables de entorno incorrectas"
echo "4. ❌ Error en el código de la aplicación"
echo "5. ❌ Problemas de configuración de Azure"
echo ""

echo "=== Soluciones Recomendadas ==="
echo ""

echo "1. 🔧 VERIFICAR Y CONFIGURAR VARIABLES DE ENTORNO"
echo "   Ve al Portal de Azure > App Service > Configuration > Application settings"
echo "   Configura las siguientes variables:"
echo ""
echo "   ALLOWED_ORIGINS=http://localhost:3005,http://localhost:3006,http://localhost:5173,http://localhost:8080,https://evaluador-frontend-fzbhemgtetfeeme6.spaincentral-01.azurestaticapps.net"
echo "   PRODUCTION=true"
echo "   HOST=0.0.0.0"
echo "   PORT=8080"
echo "   PYTHONPATH=./backend"
echo "   AZURE_OPENAI_API_KEY=4ku7UcKVerAXcTXurf4Of1aDGC5w5UreekGaLuxbsnuxOdZe48NdJQQJ99BGACR0EKYXJ3w3AAABACOGiqbl"
echo "   AZURE_OPENAI_ENDPOINT=https://teamworkzevaluate-openai.openai.azure.com"
echo "   AZURE_OPENAI_DEPLOYMENT=gpt-4o"
echo "   AZURE_OPENAI_API_VERSION=2024-11-20"
echo ""

echo "2. 🔧 VERIFICAR REQUIREMENTS.TXT"
echo "   Asegúrate de que el archivo requirements.txt esté en la raíz del proyecto"
echo "   y contenga todas las dependencias necesarias:"
echo ""
echo "   fastapi>=0.104.0"
echo "   uvicorn[standard]>=0.24.0"
echo "   python-multipart>=0.0.6"
echo "   azure-ai-documentintelligence>=1.0.0"
echo "   azure-ai-formrecognizer>=3.3.0"
echo "   openai>=1.0.0"
echo "   python-dotenv>=1.0.0"
echo "   reportlab>=4.0.0"
echo "   PyPDF2>=3.0.0"
echo "   requests>=2.31.0"
echo ""

echo "3. 🔧 CONFIGURAR STARTUP COMMAND"
echo "   En Azure App Service > Configuration > General settings:"
echo "   Startup Command: python -m uvicorn backend.main:app --host 0.0.0.0 --port 8080"
echo ""

echo "4. 🔧 REINICIAR LA APLICACIÓN"
echo "   Después de configurar las variables, reinicia la App Service"
echo ""

echo "=== Comandos Azure CLI ==="
echo ""
echo "# Verificar estado de la App Service"
echo "az webapp show --name $APP_NAME --resource-group $RESOURCE_GROUP --query state"
echo ""
echo "# Ver logs en tiempo real"
echo "az webapp log tail --name $APP_NAME --resource-group $RESOURCE_GROUP"
echo ""
echo "# Configurar variables de entorno"
echo "az webapp config appsettings set --name $APP_NAME --resource-group $RESOURCE_GROUP --settings \\"
echo "  ALLOWED_ORIGINS=\"http://localhost:3005,http://localhost:3006,http://localhost:5173,http://localhost:8080,https://evaluador-frontend-fzbhemgtetfeeme6.spaincentral-01.azurestaticapps.net\" \\"
echo "  PRODUCTION=true \\"
echo "  HOST=0.0.0.0 \\"
echo "  PORT=8080 \\"
echo "  PYTHONPATH=./backend"
echo ""
echo "# Reiniciar la App Service"
echo "az webapp restart --name $APP_NAME --resource-group $RESOURCE_GROUP"
echo ""

echo "=== Verificación Post-Configuración ==="
echo ""
echo "1. Espera 2-3 minutos después del reinicio"
echo "2. Prueba: curl $BACKEND_URL/health"
echo "3. Debería devolver: {\"status\": \"ok\"}"
echo "4. Si funciona, prueba el frontend"
echo ""

echo "=== URLs de Diagnóstico ==="
echo ""
echo "Portal de Azure: https://portal.azure.com"
echo "App Service: https://portal.azure.com/#@/resource/subscriptions/.../resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Web/sites/$APP_NAME"
echo "Logs: https://portal.azure.com/#@/resource/subscriptions/.../resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Web/sites/$APP_NAME/logs"
echo "Diagnóstico: https://$APP_NAME.scm.spaincentral-01.azurewebsites.net/detectors"
echo ""

echo "=== Próximos Pasos ==="
echo ""
echo "1. Configura las variables de entorno en Azure"
echo "2. Reinicia la App Service"
echo "3. Espera 2-3 minutos"
echo "4. Prueba: curl $BACKEND_URL/health"
echo "5. Si funciona, prueba el frontend"
echo "6. Si no funciona, revisa los logs de Azure"
echo ""
