CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE public.informes (
    id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT gen_random_uuid(),
    nombre VARCHAR(100),
    apellidos VARCHAR(100),
    email VARCHAR(150),
    whatsapp VARCHAR(20),
    discapacidad TEXT,
    tipo TEXT,
    puesto TEXT,
    jornada TEXT,
    disponibilidad TEXT,
    traslado TEXT,
    cv_text TEXT,
    decision_score INTEGER,
    resolucion_score INTEGER,
    comunicacion_score INTEGER,
    adaptabilidad_score INTEGER,
    tiempo_score INTEGER,
    equipo_score INTEGER,
    creatividad_score INTEGER,
    liderazgo_score INTEGER,
    pensamiento_score INTEGER,
    emocional_score INTEGER,
    resumen TEXT,
    fortalezas TEXT,
    areas_mejora TEXT,
    orientacion TEXT,
    conclusion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
