name: Frontend Deploy Simple

on:
  push:
    branches:
      - fix/contrast-improvement
  workflow_dispatch:

jobs:
  build_and_deploy:
    uses: ./.github/workflows/reusable-swa-deploy.yml
    secrets: inherit
    with:
      node_version: '20.x'
      app_location: 'nuevo-frontend'
      output_location: 'dist'

